CREATE DATABASE PROJECT;
USE PROJECT;

CREATE TABLE USERS (
USER_ID INT PRIMARY KEY,
USER_NAME VARCHAR(50),
AGE INT NOT NULL,
PREFERRED_GENRE VARCHAR(50)
);

INSERT INTO USERS 
(USER_ID,USER_NAME,AGE,PREFERRED_GENRE)
VALUES
(1,"OM",20,"COMEDY"),
(2,"SAI",19,"ACTION"),
(3,"RAM",20,"THRILLER"),
(4,"NIL",25,"DRAMA");

CREATE TABLE MOVIES(
MOVIE_ID INT PRIMARY KEY,
TITLE VARCHAR(50),
RELEASE_YEAR INT NOT NULL
);

INSERT INTO MOVIES
(MOVIE_ID,TITLE,RELEASE_YEAR)
VALUES
(1,"SITARAMAN", 2023),
(2,"PREMALU", 2024),
(3,"URI", 2021),
(4,"PANCHAYAT", 2025);

CREATE TABLE GENRE(
GENRE_ID INT PRIMARY KEY,
GENRE_NAME VARCHAR(50)
);

INSERT INTO GENRE
(GENRE_ID,GENRE_NAME)
VALUES
(1,"LOVE"),
(2,"COMEDY"),
(3,"ACTION"),
(4,"DRAMA");

CREATE TABLE RATINGS(
RATING_ID INT PRIMARY KEY,
RATING FLOAT CHECK (RATING BETWEEN 1 AND 5),
USER_ID INT,
MOVIE_ID INT,
RATING_DATE DATE,
FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES (MOVIE_ID)


);

INSERT INTO RATINGS
(RATING_ID,USER_ID,MOVIE_ID,RATING,RATING_DATE)
VALUES
(1,1,1,4.5,'2023-2-2'),
(2,2,2,5,'2024-12-2'),
(3,3,3,4.7,'2022-2-4'),
(4,4,4,4,'2023-5-2');

SELECT MOVIES.TITLE ,AVG(RATINGS.RATING) AS AVG_RATINGS
FROM RATINGS
JOIN MOVIES ON RATINGS.MOVIE_ID=MOVIES.MOVIE_ID
GROUP BY MOVIES.TITLE
ORDER BY AVG_RATINGS DESC;

CREATE TABLE MOVIE_GENRE(
MOVIE_ID INT,
GENRE_ID INT,
FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(MOVIE_ID),
FOREIGN KEY (GENRE_ID) REFERENCES GENRE(GENRE_ID)
);

INSERT INTO MOVIE_GENRE
(MOVIE_ID, GENRE_ID)
VALUES
(1,1),
(2,2),
(3,3),
(4,4);

SELECT MOVIES.TITLE,GENRE.GENRE_NAME
FROM MOVIES
JOIN MOVIE_GENRE ON MOVIE_GENRE.MOVIE_ID=MOVIES.MOVIE_ID
JOIN GENRE ON GENRE.GENRE_ID = MOVIE_GENRE.GENRE_ID;

SELECT MOVIES.TITLE
FROM MOVIES
WHERE RELEASE_YEAR>=2024;

SELECT USER_ID 
FROM RATINGS
JOIN MOVIES ON RATINGS.MOVIE_ID=MOVIES.MOVIE_ID;


